name: Deploy Frontend

on:
  push:
    branches: ["main"] # Запускать только для main ветки

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Get commit SHA
        id: sha
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: docker build -t stannisl/kfd-frontend:${{ steps.sha.outputs.sha }} .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker push stannisl/kfd-frontend:${{ steps.sha.outputs.sha }}
          docker tag stannisl/kfd-frontend:${{ steps.sha.outputs.sha }} stannisl/kfd-frontend:latest
          docker push stannisl/kfd-frontend:latest
